# Default values for nodepool-labels-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/banzaicloud/nodepool-labels-operator
  tag: v0.0.7
  pullPolicy: IfNotPresent

healthcheck:
  port: 8882
  endpoint: /healthz

configuration:
  log:
    format: "logfmt"
    level: "debug"

  labeler:
    managedLabelsAnnotation: "nodepool.banzaicloud.io/managed-labels"
    forbiddenLabelDomains:
    - "kubernetes.io"
    - "k8s.io"
    - "google.com"

  controller:
    namespace: "default"
    nodepoolNameLabels:
    - "nodepool.banzaicloud.io/name"
    - "cloud.google.com/gke-nodepool"
    - "agentpool"

rbac:
  enabled: true
  psp:
    enabled: false

nameOverride: ""
fullnameOverride: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
