version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
