// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/banzaicloud/nodepool-labels-operator/pkg/apis/nodepoollabelset/v1alpha1"
	scheme "github.com/banzaicloud/nodepool-labels-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodePoolLabelSetsGetter has a method to return a NodePoolLabelSetInterface.
// A group's client should implement this interface.
type NodePoolLabelSetsGetter interface {
	NodePoolLabelSets(namespace string) NodePoolLabelSetInterface
}

// NodePoolLabelSetInterface has methods to work with NodePoolLabelSet resources.
type NodePoolLabelSetInterface interface {
	Create(*v1alpha1.NodePoolLabelSet) (*v1alpha1.NodePoolLabelSet, error)
	Update(*v1alpha1.NodePoolLabelSet) (*v1alpha1.NodePoolLabelSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.NodePoolLabelSet, error)
	List(opts v1.ListOptions) (*v1alpha1.NodePoolLabelSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodePoolLabelSet, err error)
	NodePoolLabelSetExpansion
}

// nodePoolLabelSets implements NodePoolLabelSetInterface
type nodePoolLabelSets struct {
	client rest.Interface
	ns     string
}

// newNodePoolLabelSets returns a NodePoolLabelSets
func newNodePoolLabelSets(c *LabelsV1alpha1Client, namespace string) *nodePoolLabelSets {
	return &nodePoolLabelSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodePoolLabelSet, and returns the corresponding nodePoolLabelSet object, and an error if there is any.
func (c *nodePoolLabelSets) Get(name string, options v1.GetOptions) (result *v1alpha1.NodePoolLabelSet, err error) {
	result = &v1alpha1.NodePoolLabelSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.TODO()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodePoolLabelSets that match those selectors.
func (c *nodePoolLabelSets) List(opts v1.ListOptions) (result *v1alpha1.NodePoolLabelSetList, err error) {
	result = &v1alpha1.NodePoolLabelSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do(context.TODO()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodePoolLabelSets.
func (c *nodePoolLabelSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch(context.TODO())
}

// Create takes the representation of a nodePoolLabelSet and creates it.  Returns the server's representation of the nodePoolLabelSet, and an error, if there is any.
func (c *nodePoolLabelSets) Create(nodePoolLabelSet *v1alpha1.NodePoolLabelSet) (result *v1alpha1.NodePoolLabelSet, err error) {
	result = &v1alpha1.NodePoolLabelSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		Body(nodePoolLabelSet).
		Do(context.TODO()).
		Into(result)
	return
}

// Update takes the representation of a nodePoolLabelSet and updates it. Returns the server's representation of the nodePoolLabelSet, and an error, if there is any.
func (c *nodePoolLabelSets) Update(nodePoolLabelSet *v1alpha1.NodePoolLabelSet) (result *v1alpha1.NodePoolLabelSet, err error) {
	result = &v1alpha1.NodePoolLabelSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		Name(nodePoolLabelSet.Name).
		Body(nodePoolLabelSet).
		Do(context.TODO()).
		Into(result)
	return
}

// Delete takes name of the nodePoolLabelSet and deletes it. Returns an error if one occurs.
func (c *nodePoolLabelSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		Name(name).
		Body(options).
		Do(context.TODO()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodePoolLabelSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do(context.TODO()).
		Error()
}

// Patch applies the patch and returns the patched nodePoolLabelSet.
func (c *nodePoolLabelSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodePoolLabelSet, err error) {
	result = &v1alpha1.NodePoolLabelSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodepoollabelsets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.TODO()).
		Into(result)
	return
}
