---
{{- $major := .Capabilities.KubeVersion.Major -}}
{{- $minor := .Capabilities.KubeVersion.Minor -}}
{{- if and (eq (int $major) 1) (ge (int $minor) 16) }}
apiVersion: apiextensions.k8s.io/v1
{{- else }}
apiVersion: apiextensions.k8s.io/v1beta1
{{- end }}
kind: CustomResourceDefinition
metadata:
  name: nodepoollabelsets.labels.banzaicloud.io
  labels:
    app: {{ include "nodepool-labels-operator.name" . }}
    chart: {{ include "nodepool-labels-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: labels.banzaicloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: NodePoolLabelSet
    plural: nodepoollabelsets
    singular: nodepoollabelset
    shortNames:
      - npls
