---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodepoollabelsets.labels.banzaicloud.io
  labels:
    app: {{ include "nodepool-labels-operator.name" . }}
    chart: {{ include "nodepool-labels-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: labels.banzaicloud.io
  scope: Namespaced
  names:
    kind: NodePoolLabelSet
    plural: nodepoollabelsets
    singular: nodepoollabelset
    shortNames:
      - npls
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: [ "labels" ]
              properties:
                labels:
                  type: object
                  additionalProperties:
                    type: string
      served: true
      storage: true
