{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodepool-labels-operator.name" . }}
  labels:
    app: {{ include "nodepool-labels-operator.name" . }}
    chart: {{ include "nodepool-labels-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodepool-labels-operator.name" . }}
  labels:
    app: {{ include "nodepool-labels-operator.name" . }}
    chart: {{ include "nodepool-labels-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [ "labels.banzaicloud.io" ]
  resources: [ "nodepoollabelsets" ]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nodepool-labels-operator.name" . }}
  labels:
    app: {{ include "nodepool-labels-operator.name" . }}
    chart: {{ include "nodepool-labels-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "nodepool-labels-operator.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "nodepool-labels-operator.name" . }}

{{ if .Values.rbac.psp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ template "nodepool-labels-operator.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: psp:{{ template "nodepool-labels-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "nodepool-labels-operator.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "nodepool-labels-operator.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.{{ template "nodepool-labels-operator.fullname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
{{- end }}
