FROM alpine:3.13.5 AS builder

RUN apk add --update --no-cache ca-certificates


FROM alpine:3.13.5

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG BUILD_DIR
ARG BINARY_NAME

COPY config.yaml /config.yaml
COPY $BUILD_DIR/$BINARY_NAME /app

CMD ["/app"]
