---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodepoollabelsets.labels.banzaicloud.io
spec:
  group: labels.banzaicloud.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: NodePoolLabelSet
    plural: nodepoollabelsets
    singular: nodepoollabelset
    shortNames:
      - npls
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: [ "labels" ]
          properties:
            labels:
              type: object
              additionalProperties:
                type: string
              minProperties: 1
              maxProperties: 1
