---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodepool-labels-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodepool-labels-operator
rules:
- apiGroups: [ "banzaicloud.io" ]
  resources: [ "nodepoollabelsets" ]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodepool-labels-operator
subjects:
- kind: ServiceAccount
  name: nodepool-labels-operator
  namespace: default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: nodepool-labels-operator
