// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/banzaicloud/nodepool-labels-operator/pkg/apis/nodepoollabelset/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodePoolLabelSets implements NodePoolLabelSetInterface
type FakeNodePoolLabelSets struct {
	Fake *FakeLabelsV1alpha1
	ns   string
}

var nodepoollabelsetsResource = schema.GroupVersionResource{Group: "labels.banzaicloud.io", Version: "v1alpha1", Resource: "nodepoollabelsets"}

var nodepoollabelsetsKind = schema.GroupVersionKind{Group: "labels.banzaicloud.io", Version: "v1alpha1", Kind: "NodePoolLabelSet"}

// Get takes name of the nodePoolLabelSet, and returns the corresponding nodePoolLabelSet object, and an error if there is any.
func (c *FakeNodePoolLabelSets) Get(name string, options v1.GetOptions) (result *v1alpha1.NodePoolLabelSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodepoollabelsetsResource, c.ns, name), &v1alpha1.NodePoolLabelSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePoolLabelSet), err
}

// List takes label and field selectors, and returns the list of NodePoolLabelSets that match those selectors.
func (c *FakeNodePoolLabelSets) List(opts v1.ListOptions) (result *v1alpha1.NodePoolLabelSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodepoollabelsetsResource, nodepoollabelsetsKind, c.ns, opts), &v1alpha1.NodePoolLabelSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodePoolLabelSetList{ListMeta: obj.(*v1alpha1.NodePoolLabelSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodePoolLabelSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodePoolLabelSets.
func (c *FakeNodePoolLabelSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodepoollabelsetsResource, c.ns, opts))

}

// Create takes the representation of a nodePoolLabelSet and creates it.  Returns the server's representation of the nodePoolLabelSet, and an error, if there is any.
func (c *FakeNodePoolLabelSets) Create(nodePoolLabelSet *v1alpha1.NodePoolLabelSet) (result *v1alpha1.NodePoolLabelSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodepoollabelsetsResource, c.ns, nodePoolLabelSet), &v1alpha1.NodePoolLabelSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePoolLabelSet), err
}

// Update takes the representation of a nodePoolLabelSet and updates it. Returns the server's representation of the nodePoolLabelSet, and an error, if there is any.
func (c *FakeNodePoolLabelSets) Update(nodePoolLabelSet *v1alpha1.NodePoolLabelSet) (result *v1alpha1.NodePoolLabelSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodepoollabelsetsResource, c.ns, nodePoolLabelSet), &v1alpha1.NodePoolLabelSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePoolLabelSet), err
}

// Delete takes name of the nodePoolLabelSet and deletes it. Returns an error if one occurs.
func (c *FakeNodePoolLabelSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodepoollabelsetsResource, c.ns, name), &v1alpha1.NodePoolLabelSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodePoolLabelSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodepoollabelsetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodePoolLabelSetList{})
	return err
}

// Patch applies the patch and returns the patched nodePoolLabelSet.
func (c *FakeNodePoolLabelSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodePoolLabelSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodepoollabelsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodePoolLabelSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodePoolLabelSet), err
}
