// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/banzaicloud/nodepool-labels-operator/pkg/apis/nodepoollabelset/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NodePoolLabelSetLister helps list NodePoolLabelSets.
type NodePoolLabelSetLister interface {
	// List lists all NodePoolLabelSets in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.NodePoolLabelSet, err error)
	// NodePoolLabelSets returns an object that can list and get NodePoolLabelSets.
	NodePoolLabelSets(namespace string) NodePoolLabelSetNamespaceLister
	NodePoolLabelSetListerExpansion
}

// nodePoolLabelSetLister implements the NodePoolLabelSetLister interface.
type nodePoolLabelSetLister struct {
	indexer cache.Indexer
}

// NewNodePoolLabelSetLister returns a new NodePoolLabelSetLister.
func NewNodePoolLabelSetLister(indexer cache.Indexer) NodePoolLabelSetLister {
	return &nodePoolLabelSetLister{indexer: indexer}
}

// List lists all NodePoolLabelSets in the indexer.
func (s *nodePoolLabelSetLister) List(selector labels.Selector) (ret []*v1alpha1.NodePoolLabelSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NodePoolLabelSet))
	})
	return ret, err
}

// NodePoolLabelSets returns an object that can list and get NodePoolLabelSets.
func (s *nodePoolLabelSetLister) NodePoolLabelSets(namespace string) NodePoolLabelSetNamespaceLister {
	return nodePoolLabelSetNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NodePoolLabelSetNamespaceLister helps list and get NodePoolLabelSets.
type NodePoolLabelSetNamespaceLister interface {
	// List lists all NodePoolLabelSets in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.NodePoolLabelSet, err error)
	// Get retrieves the NodePoolLabelSet from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.NodePoolLabelSet, error)
	NodePoolLabelSetNamespaceListerExpansion
}

// nodePoolLabelSetNamespaceLister implements the NodePoolLabelSetNamespaceLister
// interface.
type nodePoolLabelSetNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NodePoolLabelSets in the indexer for a given namespace.
func (s nodePoolLabelSetNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.NodePoolLabelSet, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NodePoolLabelSet))
	})
	return ret, err
}

// Get retrieves the NodePoolLabelSet from the indexer for a given namespace and name.
func (s nodePoolLabelSetNamespaceLister) Get(name string) (*v1alpha1.NodePoolLabelSet, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("nodepoollabelset"), name)
	}
	return obj.(*v1alpha1.NodePoolLabelSet), nil
}
