name: Helm

on:
  push:
    branches:
      - master
  pull_request:

env:
  HELM_VERSION: v3.4.2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run helm lint
        run: |
          find -H charts/ \
            -maxdepth 2 \
            -name 'Chart.yaml' \
            -printf '%h\n' \
              | xargs helm lint
